# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/summer_design/summer_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design || ORIG_REF_NAME==summer_design} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/summer_design_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_usp_rf_data_converter_0_0 || ORIG_REF_NAME==summer_design_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_blk_mem_gen_0_0/summer_design_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_blk_mem_gen_0_0 || ORIG_REF_NAME==summer_design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_tx_blk_ram_reader_0_0/summer_design_tx_blk_ram_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_tx_blk_ram_reader_0_0 || ORIG_REF_NAME==summer_design_tx_blk_ram_reader_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_zynq_ultra_ps_e_0_0/summer_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==summer_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_proc_sys_reset_0_0/summer_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_0_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_xbar_0/summer_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_xbar_0 || ORIG_REF_NAME==summer_design_xbar_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_ps8_0_axi_periph_0/summer_design_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_ps8_0_axi_periph_0 || ORIG_REF_NAME==summer_design_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_system_ila_0_0/summer_design_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_system_ila_0_0 || ORIG_REF_NAME==summer_design_system_ila_0_0} -quiet] -quiet

# Block Designs: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/bd_9d24.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d24 || ORIG_REF_NAME==bd_9d24} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/ip/ip_0/bd_9d24_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d24_ila_lib_0 || ORIG_REF_NAME==bd_9d24_ila_lib_0} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/ip/ip_1/bd_9d24_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9d24_g_inst_0 || ORIG_REF_NAME==bd_9d24_g_inst_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_ila_0_0/summer_design_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_ila_0_0 || ORIG_REF_NAME==summer_design_ila_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_adc2axis_IQ_0_0/summer_design_adc2axis_IQ_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_adc2axis_IQ_0_0 || ORIG_REF_NAME==summer_design_adc2axis_IQ_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_proc_sys_reset_1_0/summer_design_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_1_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_axi_dma_0_0/summer_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_0 || ORIG_REF_NAME==summer_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_axi_dma_0_1/summer_design_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_1 || ORIG_REF_NAME==summer_design_axi_dma_0_1} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_system_ila_1_0/summer_design_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_system_ila_1_0 || ORIG_REF_NAME==summer_design_system_ila_1_0} -quiet] -quiet

# Block Designs: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/bd_5d75.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5d75 || ORIG_REF_NAME==bd_5d75} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/ip/ip_0/bd_5d75_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5d75_ila_lib_0 || ORIG_REF_NAME==bd_5d75_ila_lib_0} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/ip/ip_1/bd_5d75_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5d75_g_inst_0 || ORIG_REF_NAME==bd_5d75_g_inst_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_system_ila_1_1/summer_design_system_ila_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_system_ila_1_1 || ORIG_REF_NAME==summer_design_system_ila_1_1} -quiet] -quiet

# Block Designs: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/bd_9db4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9db4 || ORIG_REF_NAME==bd_9db4} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/ip/ip_0/bd_9db4_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9db4_ila_lib_0 || ORIG_REF_NAME==bd_9db4_ila_lib_0} -quiet] -quiet

# IP: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/ip/ip_1/bd_9db4_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9db4_g_inst_0 || ORIG_REF_NAME==bd_9db4_g_inst_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_proc_sys_reset_2_0/summer_design_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_2_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_auto_pc_0/summer_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_auto_pc_0 || ORIG_REF_NAME==summer_design_auto_pc_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_auto_cc_0/summer_design_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_auto_cc_0 || ORIG_REF_NAME==summer_design_auto_cc_0} -quiet] -quiet

# IP: bd/summer_design/ip/summer_design_auto_cc_1/summer_design_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==summer_design_auto_cc_1 || ORIG_REF_NAME==summer_design_auto_cc_1} -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_usp_rf_data_converter_0_0 || ORIG_REF_NAME==summer_design_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_usp_rf_data_converter_0_0 || ORIG_REF_NAME==summer_design_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_blk_mem_gen_0_0/summer_design_blk_mem_gen_0_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_zynq_ultra_ps_e_0_0/summer_design_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_zynq_ultra_ps_e_0_0/summer_design_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==summer_design_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_0_0/summer_design_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_0_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_0_0/summer_design_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_0_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9d24_ila_lib_0 || ORIG_REF_NAME==bd_9d24_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9d24_ila_lib_0 || ORIG_REF_NAME==bd_9d24_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/ip/ip_0/bd_9d24_ila_lib_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/bd_0/bd_9d24_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_0_0/summer_design_system_ila_0_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_ila_0_0 || ORIG_REF_NAME==summer_design_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_ila_0_0 || ORIG_REF_NAME==summer_design_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_ila_0_0/summer_design_ila_0_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_1_0/summer_design_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_1_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_1_0/summer_design_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_1_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_0/summer_design_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_0 || ORIG_REF_NAME==summer_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_0/summer_design_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_0 || ORIG_REF_NAME==summer_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_1/summer_design_axi_dma_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_1 || ORIG_REF_NAME==summer_design_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_1/summer_design_axi_dma_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_axi_dma_0_1 || ORIG_REF_NAME==summer_design_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5d75_ila_lib_0 || ORIG_REF_NAME==bd_5d75_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5d75_ila_lib_0 || ORIG_REF_NAME==bd_5d75_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/ip/ip_0/bd_5d75_ila_lib_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/bd_0/bd_5d75_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_0/summer_design_system_ila_1_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9db4_ila_lib_0 || ORIG_REF_NAME==bd_9db4_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9db4_ila_lib_0 || ORIG_REF_NAME==bd_9db4_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/ip/ip_0/bd_9db4_ila_lib_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/bd_0/bd_9db4_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_system_ila_1_1/summer_design_system_ila_1_1_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_2_0/summer_design_proc_sys_reset_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_2_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_2_0/summer_design_proc_sys_reset_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_proc_sys_reset_2_0 || ORIG_REF_NAME==summer_design_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_auto_pc_0/summer_design_auto_pc_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_auto_cc_0/summer_design_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_auto_cc_0 || ORIG_REF_NAME==summer_design_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_auto_cc_0/summer_design_auto_cc_0_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_auto_cc_1/summer_design_auto_cc_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==summer_design_auto_cc_1 || ORIG_REF_NAME==summer_design_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_auto_cc_1/summer_design_auto_cc_1_ooc.xdc

# XDC: d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/summer_design_ooc.xdc
