set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0_clocks.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0_clocks.xdc id:1 order:EARLY scoped_inst:summer_design_i/usp_rf_data_converter_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_0_0/summer_design_proc_sys_reset_0_0.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_0_0/summer_design_proc_sys_reset_0_0.xdc id:2 order:EARLY scoped_inst:summer_design_i/proc_sys_reset_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_1_0/summer_design_proc_sys_reset_1_0.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_1_0/summer_design_proc_sys_reset_1_0.xdc id:3 order:EARLY scoped_inst:summer_design_i/proc_sys_reset_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_0/summer_design_axi_dma_0_0.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_0/summer_design_axi_dma_0_0.xdc id:4 order:EARLY scoped_inst:summer_design_i/axi_dma_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_1/summer_design_axi_dma_0_1.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_axi_dma_0_1/summer_design_axi_dma_0_1.xdc id:5 order:EARLY scoped_inst:summer_design_i/axi_dma_1/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_2_0/summer_design_proc_sys_reset_2_0.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_proc_sys_reset_2_0/summer_design_proc_sys_reset_2_0.xdc id:6 order:EARLY scoped_inst:summer_design_i/proc_sys_reset_2/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/work/fpga/Thz/CA/prjs/summer/summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0.xdc rfile:../../../summer.gen/sources_1/bd/summer_design/ip/summer_design_usp_rf_data_converter_0_0/synth/summer_design_usp_rf_data_converter_0_0.xdc id:7 order:LATE scoped_inst:summer_design_i/usp_rf_data_converter_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:8 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:9 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:10 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:11 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:12 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:13 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:14 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:15 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:16 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl rfile:E:/vivado2023/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_handshake.tcl id:17 order:LATE scoped_inst:summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake unmanaged:yes} [current_design]
current_instance summer_design_i/usp_rf_data_converter_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_clock_sense -stop_propagation [get_pins -hier rx*_u_adc/INTERNAL_FBRC_DIV1_MUX*]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_clock_sense -stop_propagation [get_pins -hier rx*_u_adc/INTERNAL_FBRC_DIV1_MUX*]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_clock_sense -stop_propagation [get_pins -hier rx*_u_adc/INTERNAL_FBRC_DIV1_MUX*]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_clock_sense -stop_propagation [get_pins -hier rx*_u_adc/INTERNAL_FBRC_DIV1_MUX*]
current_instance
current_instance summer_design_i/proc_sys_reset_0/U0
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance summer_design_i/proc_sys_reset_1/U0
set_property src_info {type:SCOPED_XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance summer_design_i/axi_dma_0/U0
set_property src_info {type:SCOPED_XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
current_instance summer_design_i/axi_dma_1/U0
set_property src_info {type:SCOPED_XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. The Address and Data value does not change until AXI transaction is complete." -to [get_pins -hier -quiet -filter {NAME =~*I_AXI_DMA_REG_MODULE/GEN_AXI_LITE_IF.AXI_LITE_IF_I/GEN_ASYNC_WRITE.REG_WADDR_TO_IPCLK1/GENERATE_LEVEL_P_S_CDC.MULTI_BIT.FOR_IN_cdc_to[*].CROSS2_PLEVEL_IN2SCNDRY_IN_cdc_to/D}]
set_property src_info {type:SCOPED_XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -type CDC -id {CDC-1} -user "axi_dma" -tags "9601" -desc "The CDC-1 warning is waived as it is safe in the context of AXI DMA. In multi channel mode, it is safe to ignore this." -from [get_pins -hier -quiet -filter {NAME =~*MM2S_SPLIT.I_COMMAND_MM2S_SPLITTER/vsize_data_int_reg[*]/C}]
current_instance
current_instance summer_design_i/proc_sys_reset_2/U0
set_property src_info {type:SCOPED_XDC file:6 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance summer_design_i/usp_rf_data_converter_0/inst
set_property src_info {type:SCOPED_XDC file:7 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSADC_X0Y0 [get_cells -hier -filter {name =~ */rx0_u_adc}]
set_property src_info {type:SCOPED_XDC file:7 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSADC_X0Y1 [get_cells -hier -filter {name =~ */rx1_u_adc}]
set_property src_info {type:SCOPED_XDC file:7 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSADC_X0Y2 [get_cells -hier -filter {name =~ */rx2_u_adc}]
set_property src_info {type:SCOPED_XDC file:7 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSADC_X0Y3 [get_cells -hier -filter {name =~ */rx3_u_adc}]
set_property src_info {type:SCOPED_XDC file:7 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSDAC_X0Y0 [get_cells -hier -filter {name =~ */tx0_u_dac}]
set_property src_info {type:SCOPED_XDC file:7 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC HSDAC_X0Y1 [get_cells -hier -filter {name =~ */tx1_u_dac}]
set_property src_info {type:SCOPED_XDC file:7 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV1_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx1_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx1_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx1_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx1_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV1_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx1_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx2_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx2_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx2_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:149 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx2_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:154 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV1_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx2_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:161 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx3_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx3_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:171 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx3_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV2_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx3_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing ADC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_DIV1_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx3_u_adc"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx0_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:194 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx0_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:199 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx0_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:204 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx0_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:211 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:216 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==FABRIC_CLK} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:226 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-4 -tags "1033132" -description "Passing DAC outputs to the status registers" -from [list [get_pins -filter {REF_PIN_NAME==INTERNAL_FBRC_MUX} -of [get_cells -hier -filter {name =~ "*summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac"}]]] -to   [list [get_pins -filter {REF_PIN_NAME==D} -of [get_cells -hier -filter {name =~ *IP2Bus_Data_reg* && IS_SEQUENTIAL}]]]
set_property src_info {type:SCOPED_XDC file:7 line:240 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Paths wrongly related to DRP clock" -from [list [get_pins -filter {REF_PIN_NAME =~ DCLK} -of [get_cells summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc]]] -to   [list [get_pins -filter {REF_PIN_NAME =~ DATA_ADC*} -of [get_cells summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/rx0_u_adc]]]
set_property src_info {type:SCOPED_XDC file:7 line:248 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -scope -user USP_RF_DATA_CONVERTER -type CDC -id CDC-1 -tags "1033132" -description "Paths wrongly related to DRP clock" -from [list [get_pins -filter {REF_PIN_NAME =~ DCLK} -of [get_cells summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac]]] -to   [list [get_pins -filter {REF_PIN_NAME =~ DATA_DAC*} -of [get_cells summer_design_usp_rf_data_converter_0_0_rf_wrapper_i/tx1_u_dac]]]
set_property src_info {type:SCOPED_XDC file:7 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_pins -filter {REF_PIN_NAME==C} -of [get_cells -hier -filter {name =~  *tile_config/ram/data_reg[*]}]] -to [get_pins -filter {REF_PIN_NAME=~DI[*]} -of [get_cells -hier -filter {name =~ *rf_wrapper_i/*_u_*c}]] -hold  2
set_property src_info {type:SCOPED_XDC file:7 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -from [get_pins -filter {REF_PIN_NAME==C} -of [get_cells -hier -filter {name =~  *tile_config/ram/data_reg[*]}]] -to [get_pins -hierarchical -regexp {.*rf_wrapper_i\/.*_u_.*c\/DADDR\[[0-9][0]*\]}] -hold  2
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake
set_property src_info {type:SCOPED_XDC file:8 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake
set_property src_info {type:SCOPED_XDC file:9 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_ar/handshake
set_property src_info {type:SCOPED_XDC file:10 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_aw/handshake
set_property src_info {type:SCOPED_XDC file:11 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake
set_property src_info {type:SCOPED_XDC file:12 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_fwd_w/handshake
set_property src_info {type:SCOPED_XDC file:13 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake
set_property src_info {type:SCOPED_XDC file:14 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_b/handshake
set_property src_info {type:SCOPED_XDC file:15 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m01_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake
set_property src_info {type:SCOPED_XDC file:16 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
current_instance
current_instance summer_design_i/ps8_0_axi_periph/m02_couplers/auto_cc/inst/gen_clock_conv.gen_async_lite_conv.clock_conv_lite_resp_r/handshake
set_property src_info {type:SCOPED_XDC file:17 line:30 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-15} -user "xpm_cdc" -tags "1009444" -desc "The CDC-15 warning is waived as it is safe in the context of XPM_CDC_HANDSHAKE." -from [get_pins -quiet {src_hsdata_ff_reg*/C}] -to [get_pins -quiet {dest_hsdata_ff_reg*/D}]
